### ISSUE TITLE
error and reset

### ISSUE THREAD

**Issue by dony71** [tsaarni/mqtt-micropython-smartsocket#2]
repl shows below
what's wrong?

```
2 boot.py wait...
1 boot.py wait...
sys.path=['.', '', '/lib', '/']
boot.py END
2 main.py wait...
1 main.py wait...
Setup WiFi interfaces
Still connected: ('192.168.100.88', '255.255.255.0', '192.168.100.1', '10.2.1.225')
start "soft" OTA
Wait 15 sec for soft-OTA connection on port 8267
2 Reset because: soft-OTA unknown error
1 Reset because: soft-OTA unknown error

 ets Jan  8 2013,rst cause:4, boot mode:(3,6)

wdt reset
load 0x40100000, len 30668, room 16
tail 12
chksum 0x20
ho 0 tail 12 room 4
load 0x3ffe8000, len 996, room 12
tail 8
chksum 0x88
load 0x3ffe83f0, len 1064, room 0
tail 8
chksum 0xd8
csum 0xd8
▒▒▒▒x▒n▒▒r▒▒▒n▒b
▒l▒▒l`>r▒8▒l #
▒
r▒▒▒▒▒8▒▒▒
▒
r▒▒▒▒I8▒
▒▒▒
▒lrr▒9l▒Ğ▒▒
▒▒b▒▒b▒▒▒l8▒▒یxb▒▒~▒n▒boot.py
2 boot.py wait...
1 boot.py wait...
sys.path=['.', '', '/lib', '/']
boot.py END
2 main.py wait...
1 main.py wait...
Setup WiFi interfaces
Still connected: ('192.168.100.88', '255.255.255.0', '192.168.100.1', '10.2.1.225')
start webserver
restore py config _config_dim_level
Import error: no module named '_config_dim_level'
Web server started...
Still connected: ('192.168.100.88', '255.255.255.0', '192.168.100.1', '10.2.1.225')
Synchronize time from 'pool.ntp.org' ...
restore py config _config_timezone
Import error: no module named '_config_timezone'
old UTC.....: 2021-09-24T16:31:04+00:00
Task exception wasn't retrieved
future: <Task object at 3fff33e0> coro= <Task object at 3fff33e0>
Traceback (most recent call last):
  File "uasyncio/core.py", line 176, in run_until_complete
  File "./webswitch.py", line 142, in periodical_tasks
  File "./tasks.py", line 38, in periodical_tasks
  File "./ntp.py", line 71, in ntp_sync
  File "./ntp.py", line 50, in _ntp_sync
  File "./timezone.py", line 52, in localtime_isoformat
  File "./timezone.py", line 28, in restore_timezone
MemoryError: memory allocation failed, allocating 161 bytes
Watchdog reset reason: Watchdog feed timeout
Reset reason: 'Watchdog feed timeout'
Reset device: 'Watchdog feed timeout'
```

**Comment by dony71** [comment]
sorry  wrong project
